---
#
# Test Playbook
#

- hosts: localhost
  connection: local
  sudo: yes

  roles:
    - {role: ansible-mesos, mesos_install_mode: "master-slave", mesos_ip: "192.168.100.3", mesos_master_port: "5050", mesos_hostname: "localhost"}

- include: main.yml
