---
- name: Ensure dependencies are installed.
  apt: pkg=curl state=installed

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: ensure java is installed
  apt: pkg=java7-jdk state=installed

- name: Ensure Jenkins is installed.
  apt: pkg=jenkins state=installed

- name: copy libmesos to /usr/lib
  copy: src={{item}} dest=/usr/lib/{{item}}
  with_items:
    - libmesos.la
    - libmesos-0.24.1.so

- name: link libmesos.so to libmesos-0.24.1.so
  file: src=/usr/lib/libmesos-0.24.1.so dest=/usr/lib/libmesos state=link
