---
- name: update source list
  copy: src=163.source.list dest=/etc/apt/sources.list

- name:  update repository index
  apt: update_cache=yes

- name: install common packages
  apt: name={{item}} state=installed
  with_items:
    - git
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
