---

- name: add gpg key
  apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=pgp.mit.edu state=present

- name: add docker repo list
  shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list

- name: Install latest docker
  apt: pkg=docker-engine state=present update_cache=yes

- name: add extra user to group docker
  command: usermod -G docker {{extra_user}}

- name: start docker service
  service: name=docker state=started
